title: Art for days
author: Sara sabry
email: saraonthedraw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I don't know what i'm doing . . .
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  saraonthedraw # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
